### ISSUE TITLE
Getting failed installation by yarn 

### ISSUE THREAD

**Issue by sparkingdark** [labelflow/labelflow#413]
**Describe the bug**
When I try to install the dependencies using `yarn install` I got error in a package installation and so further installation failed.The message is like this:

```bash
➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable

➤ YN0000: ┌ Resolution step
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides graphql (p1aa3c) with version 15.5.1, which doesn't satisfy what @graphiql/toolkit and some of its descendants request
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides graphql (p0bb68) with version 15.5.1, which doesn't satisfy what graphiql and some of its descendants request
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides react (p9549a) with version 17.0.2, which doesn't satisfy what @labelflow/react-openlayers-fiber and some of its descendants request
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides react (pf9e09) with version 17.0.2, which doesn't satisfy what graphiql requests
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides react-dom (p7c9f2) with version 17.0.2, which doesn't satisfy what @labelflow/react-openlayers-fiber and some of its descendants request
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides react-dom (p86448) with version 17.0.2, which doesn't satisfy what graphiql requests
➤ YN0060: │ labelflow@workspace:. provides react (p5c28e) with version 17.0.2, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0060: │ labelflow@workspace:. provides react-dom (pf224e) with version 17.0.2, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 880ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ zen-observable@npm:0.8.15 can't be found in the cache and will be f
➤ YN0013: │ zustand-store-addons@npm:0.1.11 can't be found in the cache and wil
➤ YN0013: │ zustand@npm:3.5.1 can't be found in the cache and will be fetched f
➤ YN0013: │ zwitch@npm:1.0.5 can't be found in the cache and will be fetched fr
➤ YN0013: │ zwitch@npm:2.0.2 can't be found in the cache and will be fetched fr
➤ YN0000: └ Completed in 4m 28s
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ YN0007: │ cypress@npm:7.3.0 must be built because it never did before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never did before or the last one failed
➤ YN0007: │ core-js-bundle@npm:3.13.0 must be built because it never did before or the last one failed
➤ YN0007: │ core-js@npm:3.12.1 must be built because it never did before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.12.1 must be built because it never did before or the last one failed
➤ YN0007: │ nodemon@npm:2.0.12 must be built because it never did before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.14.0 must be built because it never did before or the last one failed
➤ YN0007: │ @apollo/protobufjs@npm:1.2.2 must be built because it never did before or the last one failed
➤ YN0007: │ @prisma/engines@npm:2.28.0-17.89facabd0366f63911d089156a7a70125bfbcd27 must be built because it never did before or the last one failed
➤ YN0007: │ ejs@npm:2.7.4 must be built because it never did before or the last one failed
➤ YN0007: │ prisma@npm:2.28.0 must be built because it never did before or the last one failed
➤ YN0007: │ @prisma/client@npm:2.28.0 [99545] must be built because it never did before or the last one failed
➤ YN0009: │ prisma@npm:2.28.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-e178f354/build.log)
➤ YN0009: │ prisma@npm:2.28.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-e178f354/build.log)
➤ YN0000: └ Completed in 2m 21s
➤ YN0000: Failed with errors in 6m 51s
```

**To Reproduce**
1. Go to labelflow repo
2. execure `yarn install`
3. See error

**Expected behavior**
Expected should run the project but other commands like `yarn build:web` gave error

```bash
info  - Loaded env from /home/debo/labelflow/typescript/web/.env.local

> Build error occurred
/home/debo/labelflow/typescript/web/next.config.js:76
                return callback?.();
                                ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.loadConfig [as default] (/home/debo/labelflow/node_modules/next/dist/server/config.js:345:34)

```

same thing to `yarn start:web`
```bash
eady - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/debo/labelflow/typescript/web/.env.local
/home/debo/labelflow/typescript/web/next.config.js:76
                return callback?.();
                                ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.loadConfig [as default] (/home/debo/labelflow/node_modules/next/dist/server/config.js:345:34)
```

**Desktop (please complete the following information):**
 - OS: manjaro linux
 - Version latest

**Additional context**
  -  node version 10.24.0
  -  yarn version 2.4.2
  -  npm version 7.21.0

**Comment by RaynalHugo** [comment]
Hey @sparkingdark!

Thank you for your report. 

I think this may come from the Node.js version you are using. 
Would you mind telling me the result of the command `node --version`?

On my side, it runs with v15.5.0.

**Comment by crubier** [comment]
Working on node 14.15.4 here as well

**Comment by RaynalHugo** [comment]
> I mentioned it into issue node version is 10.24

Sorry, I didn't see the Additional context part. 

Can you try with a more recent version?

**Comment by crubier** [comment]
Yeah I think you need node v14+ for this to work. 
Node v10 is deprecated 

https://nodejs.org/en/about/releases/

<img width="764" alt="Screenshot 2021-09-02 at 11 57 33" src="https://user-images.githubusercontent.com/2954572/131831997-a90e7e3c-2035-4cc0-a36b-8617b4278344.png">

**Comment by sparkingdark** [comment]
Yeah tried and it worked 
```bash
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides graphql (p1aa3c) with version 15.5.1, which doesn't satisfy what @graphiql/toolkit and some of its descendants request
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides graphql (p0bb68) with version 15.5.1, which doesn't satisfy what graphiql and some of its descendants request
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides react (p9549a) with version 17.0.2, which doesn't satisfy what @labelflow/react-openlayers-fiber and some of its descendants request
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides react (pf9e09) with version 17.0.2, which doesn't satisfy what graphiql requests
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides react-dom (p7c9f2) with version 17.0.2, which doesn't satisfy what @labelflow/react-openlayers-fiber and some of its descendants request
➤ YN0060: │ @labelflow/web@workspace:typescript/web provides react-dom (p86448) with version 17.0.2, which doesn't satisfy what graphiql requests
➤ YN0060: │ labelflow@workspace:. provides react (p5c28e) with version 17.0.2, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0060: │ labelflow@workspace:. provides react-dom (pf224e) with version 17.0.2, which doesn't satisfy what @storybook/addon-actions and some of its descendants request
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 46ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 2s 418ms
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ YN0008: │ cypress@npm:7.3.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js@npm:2.6.12 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js@npm:3.12.1 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js-pure@npm:3.12.1 must be rebuilt because its dependency tree changed
➤ YN0008: │ nodemon@npm:2.0.12 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js-pure@npm:3.14.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ @apollo/protobufjs@npm:1.2.2 must be rebuilt because its dependency tree changed
➤ YN0008: │ core-js-bundle@npm:3.13.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ @prisma/engines@npm:2.28.0-17.89facabd0366f63911d089156a7a70125bfbcd27 must be rebuilt because its dependency tree changed
➤ YN0008: │ ejs@npm:2.7.4 must be rebuilt because its dependency tree changed
➤ YN0008: │ prisma@npm:2.28.0 must be rebuilt because its dependency tree changed
➤ YN0008: │ @prisma/client@npm:2.28.0 [99545] must be rebuilt because its dependency tree changed
➤ YN0000: └ Completed in 13s 116ms
➤ YN0000: Done with warnings in 17s 450ms
```

I think you need to mention into readme file.

**Comment by crubier** [comment]
I just added the "engines" field in https://github.com/labelflow/labelflow/commit/739bd66a2fcf50751b415d379717c6d512cfbb73

**Comment by crubier** [comment]
Just checked, it's already mentioned in the [readme.md ](https://github.com/labelflow/labelflow/blob/main/README.md)

> **Prerequisites**: You need to have Git, Node (v15.5.0 or above) and Yarn (v1.22.4 or above) installed on your machine.

**Comment by sparkingdark** [comment]
great can I keep this open or close because it is working now.

**Comment by crubier** [comment]
I just closed it, thank you for our first issue from an external user 👍

**Comment by sparkingdark** [comment]
But seems I did not notice the version part that's why so a suggestion to make the specify version section more eye catching so anyone beginner user can notice that.
