### ISSUE TITLE
Fix the magic link login on workspace feature branch

### ISSUE THREAD

**Issue by nicOwlas** [labelflow/labelflow#552]
- [x] The email has labelflow.ai domain in the url (instead of the branch domain)
- [x] Cannot login even when copying the magic link token directly in the url bar with the feature branch domain name. Redirection to labelflow.ai is blocking the process.

**Comment by nacho-carnicero** [comment]
After removing setting in Vercel the `NEXTAUTH_URL` env var as production only, Vercel fallbacks successfully to the `VERCEL_URL` url for next auth which is the url of the preview deployment. This enables to receive the right link in the email instead of a link to `labelflow.ai`. The problem now is that:
- when clicking on the email the page redirection is successful but we are not logged in (no cookie set for `next-auth.session-token`
- the session is properly created in the Supabase `Session` table
- after a while the email sending stops working due to an SSL expiration problem (see screenshot below). It starts working again after some time (~1 hour) but stops working again after using the email sign in once...
<img width="1680" alt="Screenshot 2021-11-05 at 12 30 59" src="https://user-images.githubusercontent.com/17384901/140524399-8d3f48c5-c254-4546-ac56-ffb3a7e9d68e.png">

**Comment by nacho-carnicero** [comment]
This is the error I get on the remote server when clicking on the magic link : 

```
2021-11-05T14:47:44.447Z	b1d31f27-c9c8-4cec-b06e-e0b443df248d	WARN	[next-auth][warn][NEXTAUTH_URL] 
https://next-auth.js.org/warnings#nextauth_url
[Prisma Client] Initializing prismaInstance from next auth
2021-11-05T14:47:46.899Z	b1d31f27-c9c8-4cec-b06e-e0b443df248d	DEBUG	adapter_getSessionAndUser { args: [ '1b45efca-8bdd-465e-82ba-f25d5c0851c6' ] }
2021-11-05T14:47:47.527Z	b1d31f27-c9c8-4cec-b06e-e0b443df248d	ERROR	adapter_error_getSessionAndUser PrismaClientUnknownRequestError3 [PrismaClientUnknownRequestError]: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s2\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(466), routine: Some("StorePreparedStatement") }) }) })
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:36498:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getSessionAndUser (/var/task/node_modules/@next-auth/prisma-adapter/dist/index.js:22:36)
    at async acc.<computed> (/var/task/node_modules/next-auth/server/errors.js:92:16)
    at async Object.session (/var/task/node_modules/next-auth/server/routes/session.js:83:28)
    at async NextAuthHandler (/var/task/node_modules/next-auth/server/index.js:145:16)
    at async /var/task/node_modules/next-auth/server/index.js:251:32
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1014:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:901:37) {
  clientVersion: '2.30.3'
}
2021-11-05T14:47:47.530Z	b1d31f27-c9c8-4cec-b06e-e0b443df248d	ERROR	SESSION_ERROR Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s2\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(466), routine: Some("StorePreparedStatement") }) }) })
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:36498:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getSessionAndUser (/var/task/node_modules/@next-auth/prisma-adapter/dist/index.js:22:36)
    at async acc.<computed> (/var/task/node_modules/next-auth/server/errors.js:92:16)
    at async Object.session (/var/task/node_modules/next-auth/server/routes/session.js:83:28)
    at async NextAuthHandler (/var/task/node_modules/next-auth/server/index.js:145:16)
    at async /var/task/node_modules/next-auth/server/index.js:251:32
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1014:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:901:37) {
  name: 'GetSessionAndUserError'
}
```

**Comment by nacho-carnicero** [comment]
And this is the error that happens when clearing cookies + trying to sign in (the email is not even sent):

```
[POST] /api/auth/signin/email
15:10:03:06
ask/node_modules/@prisma/client/runtime/index.js:36498:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async acc.<computed> (/var/task/node_modules/next-auth/server/errors.js:92:16)
    at async Object.signin (/var/task/node_modules/next-auth/server/routes/signin.js:51:34)
    at async NextAuthHandler (/var/task/node_modules/next-auth/server/index.js:202:18)
    at async /var/task/node_modules/next-auth/server/index.js:251:32
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1014:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:901:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:210:32) {
  clientVersion: '2.30.3'
}
2021-11-05T15:10:03.342Z	e70bbeb6-14bb-4985-b569-fd34e6c39050	ERROR	Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s5\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(466), routine: Some("StorePreparedStatement") }) }) })
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:36498:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async acc.<computed> (/var/task/node_modules/next-auth/server/errors.js:92:16)
    at async Object.signin (/var/task/node_modules/next-auth/server/routes/signin.js:51:34)
    at async NextAuthHandler (/var/task/node_modules/next-auth/server/index.js:202:18)
    at async /var/task/node_modules/next-auth/server/index.js:251:32
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1014:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:901:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:210:32) {
  name: 'GetUserByEmailError'
}
2021-11-05T15:10:03.342Z	e70bbeb6-14bb-4985-b569-fd34e6c39050	ERROR	Error: Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState("42P05"), message: "prepared statement \"s5\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(466), routine: Some("StorePreparedStatement") }) }) })
    at cb (/var/task/node_modules/@prisma/client/runtime/index.js:36498:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async acc.<computed> (/var/task/node_modules/next-auth/server/errors.js:92:16)
    at async Object.signin (/var/task/node_modules/next-auth/server/routes/signin.js:51:34)
    at async NextAuthHandler (/var/task/node_modules/next-auth/server/index.js:202:18)
    at async /var/task/node_modules/next-auth/server/index.js:251:32
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils.js:102:9)
    at async Server.handleApiRequest (/var/task/node_modules/next/dist/server/next-server.js:1014:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:901:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:210:32) {
  name: 'GetUserByEmailError'
}
RequestId: e70bbeb6-14bb-4985-b569-fd34e6c39050 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by nacho-carnicero** [comment]
It was fixed by adding `&pgbouncer=true` in the URL to connect to the Supabase instance from Vercel as explained in here:
https://github.com/prisma/prisma/issues/4752#issuecomment-767101410

**Comment by RaynalHugo** [comment]
Related PR has been merged. Closing.
