### ISSUE TITLE
GitHub CI breaks randomly

### ISSUE THREAD

**Issue by bbenoist** [labelflow/labelflow#730]
## Describe the bug

Since a few days, GitHub CI randomly fails on the `Unit Tests Typescript code` phase ([example](https://github.com/labelflow/labelflow/runs/4694285388?check_suite_focus=true)).
Even on `main` 😿 

## To Reproduce

1.  Open a pull-request or merge one into `main`.
2.  They are random chances that the `Unit Tests Typescript code` CI action will fail even if if was OK on your machine.

## Expected behavior

CI unit-tests should have the same result that on our machines

**Comment by bbenoist** [comment]
Possible responsible:

```text
 PASS   browser  typescript/web/src/connectors/resolvers/__tests__/dataset.ts
  ● Console

    console.log
      Initializing database

      at Object.resetDatabase (typescript/web/src/connectors/database/index.ts:12:11)

    console.error
      <ref *1> DexieError {
        _e: Error: 
            at getErrorWithStack (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/debug.ts:29:12)
            at new DexieError (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/errors/errors.js:123:19)
            at mapError (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/errors/errors.js:154:14)
            at handleRejection (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:427:14)
            at propagateToListener (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:479:68)
            at DexiePromise._then (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:217:9)
            at /Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:408:31
            at executePromiseTask (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:401:9)
            at Listener.resolve (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:406:17)
            at callListener (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:505:18)
            at endMicroTickScope (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:583:25)
            at FDBTransaction.oncomplete (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:652:30)
            at invokeEventListeners (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/FakeEventTarget.js:67:31)
            at FDBTransaction.Object.<anonymous>.FakeEventTarget.dispatchEvent (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/FakeEventTarget.js:120:13)
            at FDBTransaction.Object.<anonymous>.FDBTransaction._start (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/FDBTransaction.js:239:22)
            at processImmediate (internal/timers.js:464:21),
        name: 'ConstraintError',
        message: 'A mutation operation in the transaction failed because a constraint was not satisfied. For example, an object such as an object store or index already exists and a request attempted to create a new one.\n' +
          ' ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. For example, an object such as an object store or index already exists and a request attempted to create a new one.',
        inner: Error [ConstraintError]: A mutation operation in the transaction failed because a constraint was not satisfied. For example, an object such as an object store or index already exists and a request attempted to create a new one.
            at new ConstraintError (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/errors.js:45:28)
            at Index.Object.<anonymous>.Index.storeRecord (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/Index.js:147:27)
            at ObjectStore.Object.<anonymous>.ObjectStore.storeRecord (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/ObjectStore.js:162:30)
            at FDBTransaction.Object.<anonymous>.FDBTransaction._start (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/FDBTransaction.js:185:34)
            at Immediate.<anonymous> (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/Database.js:28:26)
            at processImmediate (internal/timers.js:464:21),
        _promise: DexiePromise [Dexie.Promise] {
          _listeners: [],
          onuncatched: [Function: nop],
          _lib: false,
          _PSD: {
            id: 'global',
            global: true,
            ref: 2,
            unhandleds: [],
            onunhandled: [Function: globalError],
            pgp: false,
            env: [Object],
            finalize: [Function: finalize]
          },
          _stackHolder: Error: 
              at getErrorWithStack (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/debug.ts:29:12)
              at new DexiePromise (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:152:29)
              at DexiePromise.then (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:182:22)
              at Table$$1.Object.<anonymous>.Table.add (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/classes/table/table.ts:291:8)
              at Object.addDataset [as add] (/Users/bbenoist/src/labelflow/jwt/typescript/web/src/connectors/repository/dataset.ts:73:27)
              at Object.createDataset (/Users/bbenoist/src/labelflow/jwt/typescript/common-resolvers/src/dataset.ts:154:5),
          _prev: DexiePromise [Dexie.Promise] {
            _listeners: [],
            onuncatched: [Function: nop],
            _lib: false,
            _PSD: [Object],
            _stackHolder: Error: 
                at getErrorWithStack (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/debug.ts:29:12)
                at new DexiePromise (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:152:29)
                at DexiePromise.then (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:182:22)
                at tempTransaction (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/functions/temp-transaction.ts:32:8)
                at Table$$1.Object.<anonymous>.Table._trans (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/classes/table/table.ts:64:9)
                at Table$$1.Object.<anonymous>.Table.add (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/classes/table/table.ts:289:17)
                at Object.addDataset [as add] (/Users/bbenoist/src/labelflow/jwt/typescript/web/src/connectors/repository/dataset.ts:73:27)
                at Object.createDataset (/Users/bbenoist/src/labelflow/jwt/typescript/common-resolvers/src/dataset.ts:154:5),
            _prev: [DexiePromise [Dexie.Promise]],
            _numPrev: 1,
            _state: true,
            _value: [Object]
          },
          _numPrev: 2,
          _state: false,
          _value: [Circular *1]
        }
      }

      156 |     return await getDataset({ id: datasetId }, repository, user);
      157 |   } catch (e) {
    > 158 |     console.error(e);
          |             ^
      159 |     throw new Error(
      160 |       `Could not create the dataset ${JSON.stringify(
      161 |         dbDataset

      at Object.createDataset (typescript/common-resolvers/src/dataset.ts:158:13)

    console.error
      <ref *1> DexieError {
        _e: Error: 
            at getErrorWithStack (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/debug.ts:29:12)
            at new DexieError (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/errors/errors.js:123:19)
            at mapError (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/errors/errors.js:154:14)
            at handleRejection (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:427:14)
            at propagateToListener (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:479:68)
            at DexiePromise._then (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:217:9)
            at /Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:408:31
            at executePromiseTask (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:401:9)
            at Listener.resolve (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:406:17)
            at callListener (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:505:18)
            at endMicroTickScope (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:583:25)
            at FDBTransaction.oncomplete (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:652:30)
            at invokeEventListeners (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/FakeEventTarget.js:67:31)
            at FDBTransaction.Object.<anonymous>.FakeEventTarget.dispatchEvent (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/FakeEventTarget.js:120:13)
            at FDBTransaction.Object.<anonymous>.FDBTransaction._start (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/FDBTransaction.js:239:22)
            at processImmediate (internal/timers.js:464:21),
        name: 'ConstraintError',
        message: 'A mutation operation in the transaction failed because a constraint was not satisfied. For example, an object such as an object store or index already exists and a request attempted to create a new one.\n' +
          ' ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. For example, an object such as an object store or index already exists and a request attempted to create a new one.',
        inner: Error [ConstraintError]: A mutation operation in the transaction failed because a constraint was not satisfied. For example, an object such as an object store or index already exists and a request attempted to create a new one.
            at new ConstraintError (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/errors.js:45:28)
            at Index.Object.<anonymous>.Index.storeRecord (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/Index.js:147:27)
            at ObjectStore.Object.<anonymous>.ObjectStore.storeRecord (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/ObjectStore.js:162:30)
            at FDBTransaction.Object.<anonymous>.FDBTransaction._start (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/FDBTransaction.js:185:34)
            at Immediate.<anonymous> (/Users/bbenoist/src/labelflow/jwt/node_modules/fake-indexeddb/build/lib/Database.js:28:26)
            at processImmediate (internal/timers.js:464:21),
        _promise: DexiePromise [Dexie.Promise] {
          _listeners: [],
          onuncatched: [Function: nop],
          _lib: false,
          _PSD: {
            id: 'global',
            global: true,
            ref: 2,
            unhandleds: [],
            onunhandled: [Function: globalError],
            pgp: false,
            env: [Object],
            finalize: [Function: finalize]
          },
          _stackHolder: Error: 
              at getErrorWithStack (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/debug.ts:29:12)
              at new DexiePromise (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:152:29)
              at DexiePromise.then (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:182:22)
              at Table$$1.Object.<anonymous>.Table.add (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/classes/table/table.ts:291:8)
              at Object.addDataset [as add] (/Users/bbenoist/src/labelflow/jwt/typescript/web/src/connectors/repository/dataset.ts:73:27)
              at Object.createDataset (/Users/bbenoist/src/labelflow/jwt/typescript/common-resolvers/src/dataset.ts:154:5),
          _prev: DexiePromise [Dexie.Promise] {
            _listeners: [],
            onuncatched: [Function: nop],
            _lib: false,
            _PSD: [Object],
            _stackHolder: Error: 
                at getErrorWithStack (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/debug.ts:29:12)
                at new DexiePromise (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:152:29)
                at DexiePromise.then (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/helpers/promise.js:182:22)
                at tempTransaction (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/functions/temp-transaction.ts:32:8)
                at Table$$1.Object.<anonymous>.Table._trans (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/classes/table/table.ts:64:9)
                at Table$$1.Object.<anonymous>.Table.add (/Users/bbenoist/src/labelflow/jwt/node_modules/dexie/src/classes/table/table.ts:289:17)
                at Object.addDataset [as add] (/Users/bbenoist/src/labelflow/jwt/typescript/web/src/connectors/repository/dataset.ts:73:27)
                at Object.createDataset (/Users/bbenoist/src/labelflow/jwt/typescript/common-resolvers/src/dataset.ts:154:5),
            _prev: [DexiePromise [Dexie.Promise]],
            _numPrev: 1,
            _state: true,
            _value: [Object]
          },
          _numPrev: 2,
          _state: false,
          _value: [Circular *1]
        }
      }

      156 |     return await getDataset({ id: datasetId }, repository, user);
      157 |   } catch (e) {
    > 158 |     console.error(e);
          |             ^
      159 |     throw new Error(
      160 |       `Could not create the dataset ${JSON.stringify(
      161 |         dbDataset

      at Object.createDataset (typescript/common-resolvers/src/dataset.ts:158:13)
```

**Comment by valerian** [comment]
Another test that sometimes fails:

```
FAIL typescript/web/src/components/labeling-tool/image-navigation-tool-bar/__tests__/image-navigation-tool.tsx (8.49 s)
  ● should select previous image when the left arrow is pressed

    TestingLibraryElementError: Unable to find role="button"
```

**Comment by bbenoist** [comment]
https://github.com/labelflow/labelflow/runs/4729640382?check_suite_focus=true#step:9:556

**Comment by bbenoist** [comment]
https://github.com/labelflow/labelflow/runs/4727984235?check_suite_focus=true#step:9:747

**Comment by bbenoist** [comment]
https://github.com/labelflow/labelflow/runs/4730609213?check_suite_focus=true#step:9:761

**Comment by bbenoist** [comment]
It seems to have happened again 😢 Let's keep an eye on it
https://github.com/labelflow/labelflow/runs/4737926005?check_suite_focus=true#step:9:883

**Comment by bbenoist** [comment]
And again on main: https://github.com/labelflow/labelflow/runs/4740601275?check_suite_focus=true#step:9:894
Now I understand why this specific test was skipped 😢
